language: ruby

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.net#mashiro-dev" 
    use_notice: true
    skip_join: true

